cpu "8085.tbl"
hof "int8"
org 9000h
MAIN:	
CPI 00H
JZ ADD_16_BY_16
CPI 01H
JZ SUB_16_BY_16
CPI 02H
JZ MUL_8_BY_8
CPI 03H
JZ 8000H
JMP END

ADD_16_BY_16:	DAD D
JMP END
SUB_16_BY_16:	MOV A, L
SUB E
MOV L, A
MOV A, H
SBB D
MOV H, A
JMP END
MUL_8_BY_8:
;HL = D*E
MOV C, D			; C = D
MVI D, 00H			; D = 0
MVI H, 00H			; H = 0
MVI L, 00H			; L = 0
TEMP_MUL_8_BY_8:		; Temp label
DAD D				; HL = HL+E
DCR C				; C--
JNZ TEMP_MUL_8_BY_8	; LOOP
JMP END

DIV_16_BY_16:
MVI B, 00H
MVI C, 00H
; TEMP_DIV:
MOV A, L					; A = L
SUB E						; A = A-E, CY=BORROW
MOV L, A					; L = A
MOV A, H					; A = H
SUB D						; A = H-D-CY, CY=BORROW
MOV H, A					; H = A
JC 9044H		; CAN NOT SUBTRACT ANYMORE, FINISH SUBROUTINE
INX B						; BC++
JMP 9037H		; SUBTRACT AGAIN
; TEMP2_DIV:
DAD D						; HL WAS SUBTRACTED 1 EXTRA TIME(THAT IS WHY BORROW = 1, AND YOU JUMPED HERE). SO, ADD DE ONCE TO GET HL=REMAINDER
JMP END
END:
RST 5